### ISSUE TITLE
Usage in ROS2

### ISSUE THREAD

**Issue by sjahr** [fmauch/catmux#3]
I got your package working in ROS2 Eloquent Elusor. Therefore, the python packages needed to be updated to Python 3 and I changed a few things in the package.xml and setup.py, to adept the package to the ROS2 build system. Especially the changes there make the ros2 and ros1 version incompatible. Currently, I have a ros2 branch in my fork.
I'd really like to contribute my changes to your project. What do you think would be the best way to do so?

**Comment by fmauch** [comment]
I think, merging in the python3 changes does make sense (In a way that it is still compatible to python2.7)

For the rest, it might be right, to keep a ROS2 branch.

This way, the ROS-specifics could be easily maintained, if they are outside the python code itself.

**Comment by chriseichmann** [comment]
Hi @fmauch ,
I've had a look at Sebastian's fork #5 and (besides the tmux config issue discussed in #6 ) it works nicely for ROS Foxy and python3.

**Comment by chriseichmann** [comment]
Okay, there was also an issue with package lookup for ROS2.
I've fixed that on [my branch](https://github.com/chriseichmann/catmux/tree/ros2-sjahr)

I'm unsure on how to proceed. Should I open an PR or do you pull @sjahr's changes first? Or a PR against sjahr/ros2?

**Comment by fmauch** [comment]
@chriseichmann please open a new PR and state that it makes #5 obsolete.

**Comment by chriseichmann** [comment]
Hi @sjahr 
please have a look at the recent development on catmux. It's a plain python package now and easily usable with ROS2.

**Comment by fmauch** [comment]
I'll close this as mentioned above.

**Comment by sjahr** [comment]
> Hi @sjahr
> please have a look at the recent development on catmux. It's a plain python package now and easily usable with ROS2.

Sounds awesome! I will definitely try it. Thanks for taking up the work on ROS2 support :)
