### ISSUE TITLE
Make this a plain python package

### ISSUE THREAD

**Issue by fmauch** [fmauch/catmux#9]
Currently this is a catkin package. This makes it not easy (impossible?) to use in ROS2 environments as mentioned in #3 and discussed in #5 and #8.

The ROS dependency is currently only used for resolving paths using the `package://` notation. We could easily make this a ROS-independent python package by removing this functionality. This would effectively leave it to the user to resolve paths manually. On ROS the `$(rospack find <pkgname>)` notation could be used. On ROS2 there exists something similar AFAIK.

In fact, removing the ROS dependency could make this package usable for ANY tmux orchestration, not only related to ROS applications.

I'm not sure whether I am completely aware of all caveats resulting from this change which is why I created this issue (and because @chriseichmann suggested so in #8).

Benefits from migrating towards python-only:
 - No ROS dependency
 - Usable in ROS and ROS2 systems
 - Migration to python3 possible without any drawbacks. Python3 is present even on older systems where it is not the recommended python version for ROS
 - We could easily distribute it using pypi

Drawbacks:
 - More complicated filepath passing for users
 - Breaking change that would require users to change their systems using catmux if they migrate to the pypi version

**Comment by chriseichmann** [comment]
I've changed the README to reflect the new usage.
I will write a paragraph about migrating, including some info on package lookup with `rospack` and `ros2 pkg prefix`.
Maybe tag the last commit which uses catkin.

**Comment by fmauch** [comment]
Done with #10
